version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore
build_script:
- cmd: build.cmd
after_build:
- cmd: |
    7z a ShadowsocksR-netcore.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.dll %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.runtimeconfig.json
    7z a ShadowsocksR-net48.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net48\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net48\ShadowsocksR.exe.config
    7z a ShadowsocksR-netcore-win32.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\win-x86\publish\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\clean.cmd
    7z a ShadowsocksR-netcore-win64.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\win-x64\publish\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\clean.cmd
test: off
artifacts:
- path: ShadowsocksR-netcore.zip
  name: ShadowsocksR-netcore.zip
- path: ShadowsocksR-net48.zip
  name: ShadowsocksR-net48.zip
- path: ShadowsocksR-netcore-win32.zip
  name: ShadowsocksR-netcore-win32.zip
- path: ShadowsocksR-netcore-win64.zip
  name: ShadowsocksR-netcore-win64.zip